### ISSUE TITLE
emailing pam

### ISSUE THREAD

**Issue by MarconiS** [UFBI2018/workshopSpatialEcology#4]
- [x] ask for the lunches
- [x] dates (8-9 may)
- [x] topic spatial ecology stuff
- [x] hours per person

**Comment by MarconiS** [comment]
@farahcarrasco  I've assigned this to you

**Comment by farahcarrasco** [comment]
@MarconiS can't find the button to close this task, but it can be closed now

**Comment by MarconiS** [comment]
@farahcarrasco you should be able to just click on them. to close the issue you have to click on the Botton "Close and comment". Thank you so much for the email!
